title: Basic Training
description: Basic Training for new students
theme: just-the-docs

url: https://Jiayihua2001.github.io/Basic_training/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/Jiayihua2001/Basic_training.git


plugins:
  - jekyll-default-layout