title: Basic Training
description: Basic Training for new students

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://Jiayihua2001.github.io/Basic_training/

aux_links:
  Template Repository: https://github.com/Jiayihua2001/Basic_training.git

# plugins:
#   - jekyll-default-layout