source 'https://rubygems.org'

# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2
gem "base64"
gem "csv"
gem "logger"
gem "jekyll-default-layout"
gem "jekyll", "~> 4.3.4"
gem "just-the-docs"             # track the latest release; matches the deployed site's remote_theme default branch


